/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:75620fcd-432d-4401-aca2-fdc49754699b",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_qptG3wq69",
    "aws_user_pools_web_client_id": "6bk97bh087skkabmnbrs4f5g26",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://imsoxl6qnjcb3d776icbbbgaxa.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "predictions": {
        "convert": {
            "transcription": {
                "region": "us-east-2",
                "proxy": false,
                "defaults": {
                    "language": "en-US"
                }
            },
            "speechGenerator": {
                "region": "us-east-2",
                "proxy": false,
                "defaults": {
                    "VoiceId": "Kendra",
                    "LanguageCode": "en-US"
                }
            }
        }
    }
};


export default awsmobile;
