// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-east-1",
  aws_cognito_identity_pool_id:
    "us-east-1:94b99aeb-7d34-4ac7-b38f-8e82b8c2d1dc",
  aws_cognito_region: "us-east-1",
  aws_user_pools_id: "us-east-1_ZuZiMUD40",
  aws_user_pools_web_client_id: "1fkag5kje3n9r6q7q8s84eft4q",
  oauth: {},
  aws_appsync_graphqlEndpoint:
    "https://mnfvrymm4jfypo3v5mgekvuzse.appsync-api.us-east-1.amazonaws.com/graphql",
  aws_appsync_region: "us-east-1",
  aws_appsync_authenticationType: "AMAZON_COGNITO_USER_POOLS",
  predictions: {
    convert: {
      transcription: {
        region: "us-east-1",
        proxy: false,
        defaults: {
          language: "en-US"
        }
      },
      speechGenerator: {
        region: "us-east-1",
        proxy: false,
        defaults: {
          VoiceId: "Kendra",
          LanguageCode: "en-US"
        }
      }
    }
  }
};

export default awsmobile;
